Traceback (most recent call last):
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/julienprat/anaconda3/envs/book/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fontsize= 14
ticksize = 14
figsize = (12, 4.5)
params = {'font.family':'serif',
    "figure.figsize":figsize,
    'figure.dpi': 80,
    'figure.edgecolor': 'k',
    'font.size': fontsize,
    'axes.labelsize': fontsize,
    'axes.titlesize': fontsize,
    'xtick.labelsize': ticksize,
    'ytick.labelsize': ticksize
}
plt.rcParams.update(params)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 14[0m
[1;32m      3[0m figsize [38;5;241m=[39m ([38;5;241m12[39m, [38;5;241m4.5[39m)
[1;32m      4[0m params [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mfont.family[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124mserif[39m[38;5;124m'[39m,
[1;32m      5[0m     [38;5;124m"[39m[38;5;124mfigure.figsize[39m[38;5;124m"[39m:figsize,
[1;32m      6[0m     [38;5;124m'[39m[38;5;124mfigure.dpi[39m[38;5;124m'[39m: [38;5;241m80[39m,
[0;32m   (...)[0m
[1;32m     12[0m     [38;5;124m'[39m[38;5;124mytick.labelsize[39m[38;5;124m'[39m: ticksize
[1;32m     13[0m }
[0;32m---> 14[0m [43mplt[49m[38;5;241m.[39mrcParams[38;5;241m.[39mupdate(params)

[0;31mNameError[0m: name 'plt' is not defined

